version: '3.8'
services:
  mysql-db:
    image: mysql:8.0.36
    container_name: fabrica-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fabrica_db
      MYSQL_USER: admin_fabrica
      MYSQL_PASSWORD: password_seguro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: